[default]
address = "0.0.0.0"
port = 8000
temp_dir = "/tmp" # Or a path on your disk if /tmp is too small

[default.limits]
form = "50 MiB"
file = "50 MiB"
data-form = "55 MiB"

[default.shield]
x-frame-options = false

[default.tls]
key = "key.pem"     # Path or bytes to DER-encoded ASN.1 PKCS#1/#8 or SEC1 key.
certs = "cert.pem" # Path or bytes to DER-encoded X.509 TLS cert chain.